default: &default
  adapter: neo4j
  url: <%= ENV['NEO4J_BOLT_URL'] || 'bolt://neo4j:password@0.0.0.0:7687' %>
  connect_timeout: 120

development:
  <<: *default
  url: <%= ENV['NEO4J_BOLT_URL'] || 'bolt://neo4j:password@0.0.0.0:7687' %>

test:
  <<: *default
  url: <%= ENV['NEO4J_BOLT_URL'] || 'bolt://neo4j:password@0.0.0.0:7687' %>

production:
  <<: *default
  url: <%= ENV['NEO4J_BOLT_URL'] || 'bolt://neo4j:password@0.0.0.0:7687' %>